INSTALL_TARGET_PROCESSES = Instagram

TWEAK_NAME = LCTTInstagram

LCTTInstagram_FILES = Instagram.xm
LCTTInstagram_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
