export INSTALL_TARGET_PROCESSES += Instagram

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = LCTTInstagram

LCTTInstagram_FILES = Tweak.xm
LCTTInstagram_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk