include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = LCTTPrefs

LCTTPrefs_FILES = LCTTRootListController.m
LCTTPrefs_CFLAGS = -fobjc-arc
LCTTPrefs_FRAMEWORKS = UIKit
LCTTPrefs_PRIVATE_FRAMEWORKS = Preferences
LCTTPrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS_MAKE_PATH)/bundle.mk