export INSTALL_TARGET_PROCESSES += Twitter

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = LCTTTwitter

LCTTTwitter_FILES = Tweak.xm
LCTTTwitter_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk